import { User, RepairRequest } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    password: 'admin123',
    name: 'ผู้ดูแลระบบ',
    email: 'admin@university.ac.th',
    role: 'admin',
    department: 'IT Support Center',
    phone: '02-123-4567',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    username: 'tech1',
    password: 'tech123',
    name: 'สมชาย ช่างซ่อม',
    email: 'somchai@university.ac.th',
    role: 'technician',
    department: 'IT Support Center',
    phone: '02-123-4568',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    username: 'student1',
    password: 'student123',
    name: 'สมหญิง นักศึกษา',
    email: 'somying@student.university.ac.th',
    role: 'student',
    department: 'คณะวิศวกรรมศาสตร์',
    phone: '08-1234-5678',
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: '4',
    username: 'student2',
    password: 'student123',
    name: 'ประยุทธ์ วิทยา',
    email: 'prayuth@student.university.ac.th',
    role: 'student',
    department: 'คณะวิทยาศาสตร์',
    phone: '08-9876-5432',
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '5',
    username: 'student',
    password: 'student1234',
    name: 'นักศึกษา ทดสอบ',
    email: 'student@student.university.ac.th',
    role: 'student',
    department: 'คณะวิศวกรรมศาสตร์',
    phone: '08-0000-0001',
    createdAt: '2024-03-01T00:00:00Z',
  },
];

export const mockRepairRequests: RepairRequest[] = [
  {
    id: 'REQ001',
    userId: '3',
    userName: 'สมหญิง นักศึกษา',
    userEmail: 'somying@student.university.ac.th',
    userPhone: '08-1234-5678',
    department: 'คณะวิศวกรรมศาสตร์',
    equipmentType: 'คอมพิวเตอร์ตั้งโต๊ะ',
    equipmentModel: 'Dell OptiPlex 7090',
    serialNumber: 'SN123456789',
    location: 'ห้องปฏิบัติการคอมพิวเตอร์ 301 อาคาร 3',
    problemDescription: 'เครื่องเปิดไม่ติด มีเสียงบี๊บดังขึ้น 3 ครั้ง',
    priority: 'high',
    status: 'in-progress',
    assignedTo: '2',
    assignedTechnicianName: 'สมชาย ช่างซ่อม',
    createdAt: '2026-03-10T09:30:00Z',
    updatedAt: '2026-03-11T10:00:00Z',
    technicianNotes: 'ตรวจสอบแล้วพบว่า RAM ชำรุด กำลังดำเนินการเปลี่ยน',
  },
  {
    id: 'REQ002',
    userId: '4',
    userName: 'ประยุทธ์ วิทยา',
    userEmail: 'prayuth@student.university.ac.th',
    userPhone: '08-9876-5432',
    department: 'คณะวิทยาศาสตร์',
    equipmentType: 'เครื่องพิมพ์',
    equipmentModel: 'HP LaserJet Pro M404n',
    serialNumber: 'PR987654321',
    location: 'ห้องสมุด ชั้น 2',
    problemDescription: 'พิมพ์เอกสารออกมาเป็นแถบดำ',
    priority: 'medium',
    status: 'pending',
    createdAt: '2026-03-14T14:20:00Z',
    updatedAt: '2026-03-14T14:20:00Z',
  },
  {
    id: 'REQ003',
    userId: '3',
    userName: 'สมหญิง นักศึกษา',
    userEmail: 'somying@student.university.ac.th',
    userPhone: '08-1234-5678',
    department: 'คณะวิศวกรรมศาสตร์',
    equipmentType: 'โปรเจคเตอร์',
    equipmentModel: 'Epson EB-2250U',
    serialNumber: 'PJ555666777',
    location: 'ห้องเรียน 205 อาคาร 2',
    problemDescription: 'ภาพไม่ขึ้น มีเสียงแต่ไม่มีภาพ',
    priority: 'urgent',
    status: 'completed',
    assignedTo: '2',
    assignedTechnicianName: 'สมชาย ช่างซ่อม',
    createdAt: '2026-03-08T08:00:00Z',
    updatedAt: '2026-03-09T16:30:00Z',
    completedAt: '2026-03-09T16:30:00Z',
    technicianNotes: 'เปลี่ยนหลอดโปรเจคเตอร์แล้ว ใช้งานได้ปกติ',
  },
];
